spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phoneshop
    username: admin
    password: brawitadmin95
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
logging:
  level:
    liquibase: DEBUG

